---
- hosts: pancake
  tasks:
    - name: install docker
      become: yes
      apt:
        name: docker
        state: latest
    - name: install kubernetes
      become: yes
      apt:
        name: kubernetes
        state: latest    
    - name: install npm
      become: yes
      apt:
        name: npm
        state: latest    