---
- hosts: pancake

  tasks:

    - name: update ubuntu
      become: yes
      apt: update_cache=yes force_apt_get=yes 
        
    - name: install docker
      become: yes
      apt:
        name: docker
        state: latest

    - name: install docker compose
      become: yes
      apt:
        name: docker-compose
        state: latest    

    - name: install npm
      become: yes
      apt:
        name: npm
        state: latest
    
    - name: make directory for probable pancake directory
      become: yes
      file:
        path: /home/ansible/probable-pancake
        state: directory

    - name: git clone probable-pancake repo
      become: yes
      git: repo=https://github.com/jtmelhorn/probable-pancake.git dest=/home/ansible/probable-pancake